apiVersion: v1
kind: Service
metadata: 
  name: server
spec: 
  ports: 
     -  port: 8282
        protocol: TCP
        targetPort: 80
        nodePort: 31194
  selector: 
    app: server
  type: NodePort
