apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-jenkins-v01
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       80;
          server_name  _;
          location / {
            proxy_pass http://localhost:8080/;
          }
      }
    }
