apiVersion: v1
kind: Service
metadata: 
  name: jenkins-web
spec: 
  ports: 
     -  port: 8181
        protocol: TCP
        targetPort: 80
        nodePort: 31193
  selector: 
    app: webserver
  type: NodePort
